server:
  port: 8088

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true

spring:
  application:
    name: COMMENT-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/opgmap_comment

  liquibase:
    change-log: classpath:changelog/changelog-master.yml

  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8888/realms/opgmap/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  swagger-ui:
    oauth:
      clientId: swagger
      clientSecret: fsTR31mMbOEOl9FSNw6oIZFGyVz8fYhY
      use-pkce-with-authorization-code-grant: true
  oAuthFlow:
    authorizationUrl: http://localhost:8888/realms/opgmap/protocol/openid-connect/auth
    tokenUrl: http://localhost:8888/realms/opgmap/protocol/openid-connect/token

logging:
  level:
    org:
      springframework:
        security: DEBUG